/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "Options": "选项",
    "points to prestige.": "点数到声望。",
    "Points.": "点数.",
    "Prestige points.": "声望点。",
    "Reach": "达到",
    "research points.": "研究点。",
    "Reset without gaining prestige points.": "在不获得声望点的情况下重置。",
    "Respec Tree Upgrades data: {{ player.prestige.respec?'ON':'OFF' }}": "重洗树升级数据: {{ player.prestige.respec?'开':'关' }}",
    "Tree Upgrades: {{ player.canvas.upgArray.length }}/100": "树升级: {{ player.canvas.upgArray.length }}/100",
    "Treemental": "精神树",
    "WIPE": "擦除",
    "When respec that, will back to previous floor.": "当 重洗 时，将回到上一层。",
    "Zoom": "缩放",
    "Go to next floor {{ format(player.floor+1, 0) }}": "前往下一层 {{ format(player.floor+1, 0) }}",
    "Have 5% chance to generate tree upgrade for getting research.": "有 5% 的几率生成树升级以进行研究。",
    "Gain": "获得",
    "Floor {{ format(player.floor, 0) }}": "层 {{ format(player.floor, 0) }}",
    "Active": "激活",
    "Buy": "购买",
    "Buy All Upgrades [M]": "购买全部升级 [M]",
    "[2] Unspent points boost points gain at reduced rate.": "[2] 未花费点数以降低的速度增加点数。",
    "[3] Gain more points based on tree upgrades bought.": "[3] 根据购买的树升级获得更多点数。",
    "Level: {{ format(FUNCTIONS.buyables.research.have(x),0) }}": "等级: {{ format(FUNCTIONS.buyables.research.have(x),0) }}",
    "Unspent points boost points gain at reduced rate.": "未花费点数以降低的速度增加点数。",
    "Start to generate Points.": "开始生成点数。",
    "Gain more points based on unspent Prestige points.": "根据未使用的声望点获得更多点数。",
    "Gain more prestige points based on unspent prestige points.": "根据未使用的声望点获得更多声望点。",
    "Prestige": "声望",
    "Raise points gain by 1.15.": "提高点数增益 1.15。",
    "Remove first Tree upgrade for multiplier.": "删除第一个树升级的乘数。",
    "Tree upgrade \"Gain more points based on tree upgrades bought.\" is raised by 2.": "树升级“根据购买的树升级获得更多点数。”提高 2。",
    "Tree Upgrades are 12.5% stronger.": "树升级强度提高 12.5%。",
    "Tree Upgrades are stronger based on your floor.": "根据您的层数，树升级更强大。",
    "Unlock new tree upgrades (can spawn from generation only over 50 Tree Upgrades created).": "解锁新的树升级（只能从生成超过 50 个树升级创建）。",
    "Unlock Research.": "解锁研究。",
    "Raise research points gain by 1.25.": "将研究点数增益提高 1.25。",
    "Research": "研究",
    "Raise tree upgrades 2-3 by 2.5.": "将树升级 2-3 提高 2.5。",
    "Research buyables 1 are 50% stronger.": "研究可购买 1 的强度提高了 50%。",
    "Unlock Auto-Buy Tree Upgrades.": "解锁自动购买树升级。",
    "Can generate 4th tree upgrade instead of over 50 generated.": "可以生成第 4 树升级而不是生成超过 50。",
    "Gain more points.": "获得更多点数。",
    "Gain more prestige points based on unspent research points.": "根据未花费的研究点数获得更多声望点数。",
    "Gain more prestige points.": "获得更多声望点。",
    "Gain more research points based on unspent points.": "根据未花费的点数获得更多的研究点数。",
    "Gain more research points.": "获得更多的研究点。",
    "Get 128 research points.": "获得 128 个研究点。",
    "[4] Unspent prestige points boost points at reduced rate.": "[4] 未使用的声望点数以降低的速度增加点数。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Currently: ": "当前: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^当前: ([\d\.]+)x$/,
    /^成本： (.+) 声望点$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\/s\)$/,
    /^([\d\.]+)e([\d\.,]+)\/s\)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Cost: (.+) PP$/, '成本： $1 声望点'],
    [/^Cost: (.+) RP$/, '成本： $1 研究点'],
    [/^Cost: (.+) Points.$/, '成本： $1 点数。'],
    [/^\[([\d\.]+)\] Gain ([\d\.]+)x more points.$/, '\[$1\] 获得更多 $2x 点数.'],
    [/^Gain ([\d\.]+)x more points.$/, '获得更多 $1x 点数.'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+) boughts left$/, '购买剩余 $1'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);